name: Test
on:
  pull_request:

jobs:
  run-pytest:
    name: Run unit/functional tests
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run pytest
      run: make pytest

  run-bandit:
    name: Run bandit static analysis
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run bandit
      run: make bandit
